name: Build Assistant

on:
  workflow_dispatch:
    inputs:
      openai_api_key:
        description: "OpenAI API key"
        required: true
        default: ""

jobs:
  run-build-assistant:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Assistant dependencies
        run: |
          python -m pip install hatch
          hatch env create
      - name: Unit Assistant tests
        run: |
          hatch run test
      - name: Run Build Assistant
        env:
          OPENAI_API_KEY: ${{ github.event.inputs.openai_api_key }}
        run: |
          hatch run build
